Gocode pkg: "github.com/bertabus/swole"
Gocode env: gocode.margoEnv{LibPath:"/usr/lib/go/pkg/linux_amd64:/home/bertabus/go/pkg/linux_amd64", GOOS:"linux", GOARCH:"amd64", Compiler:"gc", GOROOT:"/usr/lib/go", GOPATH:"/home/bertabus/go", InstallSuffix:""}
Gocode pkg: "github.com/bertabus/swole"
Gocode env: gocode.margoEnv{LibPath:"/usr/lib/go/pkg/linux_amd64:/home/bertabus/go/pkg/linux_amd64", GOOS:"linux", GOARCH:"amd64", Compiler:"gc", GOROOT:"/usr/lib/go", GOPATH:"/home/bertabus/go", InstallSuffix:""}
Gocode pkg: "github.com/bertabus/swole"
Gocode env: gocode.margoEnv{LibPath:"/usr/lib/go/pkg/linux_amd64:/home/bertabus/go/pkg/linux_amd64", GOOS:"linux", GOARCH:"amd64", Compiler:"gc", GOROOT:"/usr/lib/go", GOPATH:"/home/bertabus/go", InstallSuffix:""}
Gocode pkg: "github.com/bertabus/swole"
Gocode env: gocode.margoEnv{LibPath:"/usr/lib/go/pkg/linux_amd64:/home/bertabus/go/pkg/linux_amd64", GOOS:"linux", GOARCH:"amd64", Compiler:"gc", GOROOT:"/usr/lib/go", GOPATH:"/home/bertabus/go", InstallSuffix:""}
Gocode pkg: "github.com/bertabus/swole"
Gocode env: gocode.margoEnv{LibPath:"/usr/lib/go/pkg/linux_amd64:/home/bertabus/go/pkg/linux_amd64", GOOS:"linux", GOARCH:"amd64", Compiler:"gc", GOROOT:"/usr/lib/go", GOPATH:"/home/bertabus/go", InstallSuffix:""}
Gocode pkg: "github.com/bertabus/swole"
Gocode env: gocode.margoEnv{LibPath:"/usr/lib/go/pkg/linux_amd64:/home/bertabus/go/pkg/linux_amd64", GOOS:"linux", GOARCH:"amd64", Compiler:"gc", GOROOT:"/usr/lib/go", GOPATH:"/home/bertabus/go", InstallSuffix:""}
Gocode pkg: "github.com/bertabus/swole"
Gocode env: gocode.margoEnv{LibPath:"/usr/lib/go/pkg/linux_amd64:/home/bertabus/go/pkg/linux_amd64", GOOS:"linux", GOARCH:"amd64", Compiler:"gc", GOROOT:"/usr/lib/go", GOPATH:"/home/bertabus/go", InstallSuffix:""}
Gocode pkg: "github.com/bertabus/swole"
Gocode env: gocode.margoEnv{LibPath:"/usr/lib/go/pkg/linux_amd64:/home/bertabus/go/pkg/linux_amd64", GOOS:"linux", GOARCH:"amd64", Compiler:"gc", GOROOT:"/usr/lib/go", GOPATH:"/home/bertabus/go", InstallSuffix:""}
Gocode pkg: "github.com/bertabus/CleaningList"
Gocode env: gocode.margoEnv{LibPath:"/usr/lib/go/pkg/linux_amd64:/home/bertabus/go/pkg/linux_amd64", GOOS:"linux", GOARCH:"amd64", Compiler:"gc", GOROOT:"/usr/lib/go", GOPATH:"/home/bertabus/go", InstallSuffix:""}
Gocode pkg: "github.com/bertabus/CleaningList"
Gocode env: gocode.margoEnv{LibPath:"/usr/lib/go/pkg/linux_amd64:/home/bertabus/go/pkg/linux_amd64", GOOS:"linux", GOARCH:"amd64", Compiler:"gc", GOROOT:"/usr/lib/go", GOPATH:"/home/bertabus/go", InstallSuffix:""}
Gocode pkg: "github.com/bertabus/CleaningList"
Gocode env: gocode.margoEnv{LibPath:"/usr/lib/go/pkg/linux_amd64:/home/bertabus/go/pkg/linux_amd64", GOOS:"linux", GOARCH:"amd64", Compiler:"gc", GOROOT:"/usr/lib/go", GOPATH:"/home/bertabus/go", InstallSuffix:""}
Gocode pkg: "github.com/bertabus/CleaningList"
Gocode env: gocode.margoEnv{LibPath:"/usr/lib/go/pkg/linux_amd64:/home/bertabus/go/pkg/linux_amd64", GOOS:"linux", GOARCH:"amd64", Compiler:"gc", GOROOT:"/usr/lib/go", GOPATH:"/home/bertabus/go", InstallSuffix:""}
Gocode pkg: "github.com/bertabus/CleaningList"
Gocode env: gocode.margoEnv{LibPath:"/usr/lib/go/pkg/linux_amd64:/home/bertabus/go/pkg/linux_amd64", GOOS:"linux", GOARCH:"amd64", Compiler:"gc", GOROOT:"/usr/lib/go", GOPATH:"/home/bertabus/go", InstallSuffix:""}
Gocode pkg: "github.com/bertabus/CleaningList"
Gocode env: gocode.margoEnv{LibPath:"/usr/lib/go/pkg/linux_amd64:/home/bertabus/go/pkg/linux_amd64", GOOS:"linux", GOARCH:"amd64", Compiler:"gc", GOROOT:"/usr/lib/go", GOPATH:"/home/bertabus/go", InstallSuffix:""}
Gocode pkg: "github.com/bertabus/CleaningList"
Gocode env: gocode.margoEnv{LibPath:"/usr/lib/go/pkg/linux_amd64:/home/bertabus/go/pkg/linux_amd64", GOOS:"linux", GOARCH:"amd64", Compiler:"gc", GOROOT:"/usr/lib/go", GOPATH:"/home/bertabus/go", InstallSuffix:""}
Gocode pkg: "github.com/bertabus/GoHome"
Gocode env: gocode.margoEnv{LibPath:"/usr/lib/go/pkg/linux_amd64:/home/bertabus/go/pkg/linux_amd64", GOOS:"linux", GOARCH:"amd64", Compiler:"gc", GOROOT:"/usr/lib/go", GOPATH:"/home/bertabus/go", InstallSuffix:""}
Gocode pkg: "github.com/bertabus/GoHome"
Gocode env: gocode.margoEnv{LibPath:"/usr/lib/go/pkg/linux_amd64:/home/bertabus/go/pkg/linux_amd64", GOOS:"linux", GOARCH:"amd64", Compiler:"gc", GOROOT:"/usr/lib/go", GOPATH:"/home/bertabus/go", InstallSuffix:""}
Gocode pkg: "github.com/bertabus/GoHome"
Gocode env: gocode.margoEnv{LibPath:"/usr/lib/go/pkg/linux_amd64:/home/bertabus/go/pkg/linux_amd64", GOOS:"linux", GOARCH:"amd64", Compiler:"gc", GOROOT:"/usr/lib/go", GOPATH:"/home/bertabus/go", InstallSuffix:""}

** 2017-10-22 20:01:51.845424 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-22 20:01:51.847732 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-22 20:01:51.849679 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-22 20:26:21.561725 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-22 20:26:21.563484 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-22 20:26:21.564616 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-22 22:14:38.258174 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-22 22:14:38.260175 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-22 22:14:38.261616 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-22 22:16:59.239774 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-22 22:16:59.241871 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-22 22:16:59.243711 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-23 15:41:00.583939 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-23 15:41:00.586302 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-23 15:41:00.588410 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-23 15:44:54.582274 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-23 15:44:54.583749 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-23 15:44:54.585779 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 16:52:22.183431 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 16:52:22.185564 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 16:52:22.186744 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 16:52:56.490414 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 16:52:56.492440 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 16:52:56.500980 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 16:56:19.894022 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 16:56:19.896662 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 16:56:19.903064 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 16:56:38.813035 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 16:56:38.815690 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 16:56:38.817958 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:08:43.314936 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:08:43.317201 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:08:43.318627 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:10:24.284336 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:10:24.285775 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:10:24.288347 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:10:54.677459 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:10:54.679794 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:10:54.686246 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:11:53.611000 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:11:53.612815 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:11:53.619509 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:12:02.315928 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:12:02.321812 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:12:02.324923 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:12:46.834860 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:12:46.836728 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:12:46.838108 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:17:11.286276 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:17:11.288005 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:17:11.288974 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:17:29.799538 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:17:29.802457 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:17:29.804377 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:17:46.332708 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:17:46.335010 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:17:46.336103 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:18:10.249857 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:18:10.252025 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:18:10.253648 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:19:06.797690 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:19:06.800014 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:19:06.802588 **:
GsLint: GoSublime: Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 297, in env
    uenv[k] = string.Template(uenv[k]).safe_substitute(e)
  File "./python3.3/string.py", line 148, in safe_substitute
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 104, in run
    p, opts, err = proc(cmd, input=input, shell=shell, stderr=stderr, env=env, cwd=cwd)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 51, in proc
    env = sh.env(env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/sh.py", line 299, in env
    gs.println('%s: Cannot expand env var `%s`: %s' % (NAME, k, ex))
NameError: global name 'NAME' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gslint.py", line 229, in do_comp_lint
    out, err, _ = gsshell.run(cmd=cmd, shell=shell, cwd=dirname, env=env)
  File "/home/bertabus/.config/sublime-text-3/Packages/GoSublime/gosubl/gsshell.py", line 109, in run
    err = u'Error communicating with command %s: %s' % (opts.get('cmd'), gs.traceback())
UnboundLocalError: local variable 'opts' referenced before assignment
--------------------------------

** 2017-10-25 17:20:36.065457 **:
MarGo: Missing required environment variables: GOROOT
See the `Quirks` section of USAGE.md for info
--------------------------------
Gocode pkg: "github.com/bertabus/GoHome"
Gocode env: gocode.margoEnv{LibPath:"/home/bertabus/go/pkg/linux_amd64", GOOS:"linux", GOARCH:"amd64", Compiler:"gc", GOROOT:"", GOPATH:"/home/bertabus/go", InstallSuffix:""}
Gocode pkg: "github.com/bertabus/GoHome"
Gocode env: gocode.margoEnv{LibPath:"/usr/lib/go/pkg/linux_amd64:/home/bertabus/go/pkg/linux_amd64", GOOS:"linux", GOARCH:"amd64", Compiler:"gc", GOROOT:"/usr/lib/go", GOPATH:"/home/bertabus/go", InstallSuffix:""}
Gocode pkg: "github.com/bertabus/GoHome"
Gocode env: gocode.margoEnv{LibPath:"/usr/lib/go/pkg/linux_amd64:/home/bertabus/go/pkg/linux_amd64", GOOS:"linux", GOARCH:"amd64", Compiler:"gc", GOROOT:"/usr/lib/go", GOPATH:"/home/bertabus/go", InstallSuffix:""}
Gocode pkg: "github.com/bertabus/GoHome"
Gocode env: gocode.margoEnv{LibPath:"/usr/lib/go/pkg/linux_amd64:/home/bertabus/go/pkg/linux_amd64", GOOS:"linux", GOARCH:"amd64", Compiler:"gc", GOROOT:"/usr/lib/go", GOPATH:"/home/bertabus/go", InstallSuffix:""}
Gocode pkg: "github.com/bertabus/GoHome"
Gocode env: gocode.margoEnv{LibPath:"/usr/lib/go/pkg/linux_amd64:/home/bertabus/go/pkg/linux_amd64", GOOS:"linux", GOARCH:"amd64", Compiler:"gc", GOROOT:"/usr/lib/go", GOPATH:"/home/bertabus/go", InstallSuffix:""}
